"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.2.
...
"""

from pathlib import Path
from datetime import timedelta # <-- CORRECCIÓN: Se añade este import.

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-(nyydbaz(@h6b436onb6f=kkfq_kl3^96(h^d)c6#$ncv$l#34'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    # Django apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Terceros (Actualizados)
    'rest_framework',
    'corsheaders',
    'rest_framework_simplejwt',
    'rest_framework.authtoken',

    # Nuestra app
    'invex',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'invex_db',
        'USER': 'postgres',
        'PASSWORD': 'AKAMARU',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}


# Password validation
# ... (Sin cambios)

# Internationalization
# ... (Sin cambios)

# Static files (CSS, JavaScript, Images)
# ... (Sin cambios)

# Default primary key field type
# ... (Sin cambios)

AUTH_USER_MODEL = 'invex.Usuario'

# ===============================================
# CONFIGURACIONES DE DRF, CORS y JWT
# ===============================================

# 1. Configuración de Django Rest Framework
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    )
}

# 2. Configuración de CORS para Vue.js
CORS_ALLOWED_ORIGINS = [
    "http://localhost:8080",
    "http://127.0.0.1:8080",
    "http://localhost:5173",
]

# 3. CONFIGURACIÓN DE SIMPLE JWT (VERSIÓN FINAL Y COMPLETA)
SIMPLE_JWT = {
   'ACCESS_TOKEN_LIFETIME': timedelta(minutes=5), # <-- CORRECCIÓN: El token expira en 5 minutos.
   'REFRESH_TOKEN_LIFETIME': timedelta(days=1),   # <-- CORRECCIÓN: El token de refresco dura 1 día.

   'SIGNING_KEY': SECRET_KEY,
   'AUTH_HEADER_TYPES': ('Bearer',),
}

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Directorio donde Django recolectará los archivos estáticos
STATIC_ROOT = BASE_DIR / 'staticfiles'