"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.2.
...
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-(nyydbaz(@h6b436onb6f=kkfq_kl3^96(h^d)c6#$ncv$l#34'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    # Django apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Terceros (Actualizados)
    'rest_framework',
    'corsheaders',              # <-- Añadido para la comunicación con Vue
    'rest_framework.authtoken', # <-- Añadido para la autenticación por Token

    # Nuestra app
    'invex',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',        # <-- Añadido: DEBE IR AL PRINCIPIO
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'invex_db',           
        'USER': 'postgres',           
        'PASSWORD': 'AKAMARU',         
        'HOST': 'localhost',          
        'PORT': '5432',               
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators
# ... (Sin cambios)


# Internationalization
# ... (Sin cambios)


# Static files (CSS, JavaScript, Images)
# ... (Sin cambios)


# Default primary key field type
# ... (Sin cambios)


AUTH_USER_MODEL = 'invex.Usuario'

# ===============================================
# NUEVAS CONFIGURACIONES DE DRF y CORS
# ===============================================

# 1. Configuración de Django Rest Framework (DRF)
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication', 
    )
}

# 2. Configuración de CORS para Vue.js
# Esto permite que tu frontend Vue (ej: en puerto 8080 o 5173) se comunique con Django (puerto 8000)
CORS_ALLOW_ALL_ORIGINS = True # *Ideal para desarrollo local*
# CORS_ALLOWED_ORIGINS = [ # Opción más segura, puedes habilitarla más tarde
#     "http://localhost:8080",
#     "http://127.0.0.1:8080",
#     "http://localhost:5173",
# ]

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# NUEVA CONFIGURACIÓN: Directorio donde Django recolectará los archivos estáticos
STATIC_ROOT = BASE_DIR / 'staticfiles' 