# Generated by Django 5.2.7 on 2025-10-13 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invex', '0002_categoria_producto_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='rubro',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='empresa',
            name='rut',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
