# Generated by Django 5.2.7 on 2025-10-13 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invex', '0002_categoria_producto_categoria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name_plural': 'Categorías'},
        ),
        migrations.AlterModelOptions(
            name='usuarioempresa',
            options={'verbose_name': 'Relación Usuario-Empresa', 'verbose_name_plural': 'Relaciones Usuario-Empresa'},
        ),
        migrations.AddField(
            model_name='producto',
            name='sku',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='demanda_estacional',
            field=models.CharField(default='Normal', max_length=100),
        ),
    ]
