# Generated by Django 5.2.7 on 2025-10-13 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invex', '0003_empresa_rubro_empresa_rut'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='mostrar_tutorial',
            field=models.BooleanField(default=True),
        ),
    ]
