# Generated by Django 5.2.7 on 2025-10-15 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invex', '0003_alter_categoria_options_alter_usuarioempresa_options_and_more'),
        ('invex', '0004_usuario_mostrar_tutorial'),
    ]

    operations = [
    ]
