# Generated by Django 5.2.7 on 2025-10-15 23:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invex', '0005_merge_20251014_2231'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proveedores', to='invex.empresa')),
            ],
            options={
                'unique_together': {('empresa', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('venta', 'Venta'), ('compra', 'Compra'), ('ajuste', 'Ajuste de Stock')], max_length=10)),
                ('cantidad', models.IntegerField()),
                ('unidad_medida', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_compra_producto', models.DateField(default=django.utils.timezone.now)),
                ('fecha_pedido', models.DateField(blank=True, null=True)),
                ('fecha_recepcion', models.DateField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='invex.producto')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invex.proveedor')),
            ],
            options={
                'verbose_name_plural': 'Movimientos de Inventario',
                'ordering': ['-fecha_compra_producto'],
            },
        ),
    ]
