# Generated by Django 5.2.7 on 2025-10-16 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invex', '0006_proveedor_movimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaimportante',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
