# Generated by Django 5.2.7 on 2025-11-09 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invex', '0007_diaimportante_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='dias_analisis_demanda',
            field=models.PositiveIntegerField(default=90, help_text='Días históricos para calcular demanda promedio'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='semanas_objetivo',
            field=models.PositiveIntegerField(default=4, help_text='Semanas objetivo de stock al realizar una compra'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='semanas_seguridad',
            field=models.PositiveIntegerField(default=2, help_text='Semanas de stock de seguridad antes de comprar'),
        ),
    ]
