# Generated by Django 5.2.7 on 2025-11-20 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invex', '0008_empresa_dias_analisis_demanda_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, help_text='Fecha de caducidad del lote comprado', null=True),
        ),
    ]
