# Generated by Django 5.2.7 on 2025-11-21 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invex', '0009_movimiento_fecha_vencimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='buffer_venta_semanas',
            field=models.PositiveIntegerField(default=2, help_text='Semanas antes del vencimiento para dejar de sugerir compra (margen de seguridad)'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='lead_time_defecto',
            field=models.PositiveIntegerField(default=7, help_text='Días que tarda un proveedor si no hay historial previo (para productos nuevos)'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='max_lead_time_razonable',
            field=models.PositiveIntegerField(default=60, help_text='Días máximos para considerar una compra válida en el historial (filtro de errores)'),
        ),
    ]
