# Generated by Django 5.2.7 on 2025-11-21 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invex', '0010_empresa_buffer_venta_semanas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='umbral_demanda_minima',
            field=models.FloatField(default=0.5, help_text='Ventas semanales mínimas para considerar que un producto tiene demanda activa'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='umbral_sobrestock_semanas',
            field=models.PositiveIntegerField(default=12, help_text='Semanas de cobertura máximas antes de marcar el producto como Sobrestock'),
        ),
    ]
