# Generated by Django 5.2.7 on 2025-11-28 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invex', '0011_empresa_umbral_demanda_minima_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='subscription_status',
            field=models.CharField(choices=[('free', 'Free'), ('pro', 'Pro')], default='free', max_length=20),
        ),
    ]
