# Generated by Django 5.2.7 on 2025-12-06 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invex', '0013_historialinventario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='subscription_status',
        ),
        migrations.AddField(
            model_name='empresa',
            name='subscription_status',
            field=models.CharField(choices=[('free', 'Free'), ('pro', 'Pro')], default='free', max_length=20),
        ),
    ]
