# Generated by Django 5.2.7 on 2025-12-06 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invex', '0014_remove_usuario_subscription_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='sku',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.UniqueConstraint(condition=models.Q(('sku__isnull', False)), fields=('empresa', 'sku'), name='unique_sku_per_empresa'),
        ),
    ]
